# Generated by Django 6.0.3 on 2026-03-03 17:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Documento')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo')),
                ('telefono_fijo', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono fijo válido (7 a 10 dígitos, sin prefijo).', regex='^\\d{7,10}$')], verbose_name='Teléfono fijo')),
                ('celular', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de celular válido con prefijo (+57..., mínimo 10 y máximo 15 dígitos).', regex='^\\+\\d{10,15}$')], verbose_name='Celular')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('tipo', models.CharField(choices=[('regular', 'Regular'), ('frecuente', 'Frecuente'), ('vip', 'VIP´S')], default='regular', max_length=10, verbose_name='Tipo de cliente')),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas internas')),
                ('fechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['-fechaRegistro'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])])),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('abono', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('restante', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('pago_completo', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='gestion_app.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_app.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion_app.venta')),
            ],
        ),
    ]
